# syntax=docker/dockerfile:1

FROM --platform=$BUILDPLATFORM node:24-alpine3.24 AS webui
ENV VITE_APP_BASE_URL=""
ENV VITE_APP_BASE_API_URL="/api"
WORKDIR /src/webui
COPY webui/package.json webui/yarn.lock webui/.yarnrc.yml ./
RUN npm i -g corepack && yarn workspaces focus --all --production
COPY webui/ ./
RUN yarn build:prod

FROM --platform=$BUILDPLATFORM golang:1.26 AS build
WORKDIR /src
COPY . .
COPY --from=webui /src/webui/static/ ./webui/static/
ARG TARGETOS
ARG TARGETARCH
ARG VERSION=dev
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build \
    -ldflags "-s -w -X github.com/traefik/traefik/v3/pkg/version.Version=${VERSION} -X github.com/traefik/traefik/v3/pkg/version.Codename=cheddar" \
    -installsuffix nocgo -o /out/traefik ./cmd/traefik

FROM alpine:3.24
RUN apk add --no-cache --no-progress ca-certificates tzdata
COPY --from=build /out/traefik /
EXPOSE 80
VOLUME ["/tmp"]
ENTRYPOINT ["/traefik"]
